### ISSUE TITLE
[feature] PYTHON_TARGETS for python:3.x support

### ISSUE THREAD

**Issue by msva** [gentoo/elogv#5]

**Comment by hartwork** [comment]
Please elaborate on what is wanted, exactly.

**Comment by jaakristioja** [comment]
Currently, `app-portage/elogv` only allows `PYTHON_TARGETS="python2_7"`. I presume the issue is about supporting Python 3 as well. Personally, I also want to remove Python 2 from some of my Gentoo machines.

**Comment by hartwork** [comment]
Pull requests welcome, no time myself.
